### ISSUE TITLE
[Feature] Save config after launching

### ISSUE THREAD

**Issue by guikarist** [guikarist/rl-framework#20]
Save a configuration file locally after starting

**Comment by AltmanD** [comment]
Already complete

**Comment by AltmanD** [comment]
Already complete in [commmit b349c26](https://github.com/guikarist/rl-framework/pull/29/commits/b349c266769464ece95761c1d5a4dd27ba2ea56f)

**Comment by terryzhao127** [comment]
> Already complete in [commmit b349c26](https://github.com/guikarist/rl-framework/pull/29/commits/b349c266769464ece95761c1d5a4dd27ba2ea56f)

Not quite good.
Re-implemented in #30.
