### ISSUE TITLE
[Bug] 'export_config()' can't return configs properly

### ISSUE THREAD

**Issue by AltmanD** [guikarist/rl-framework#27]
When I call 'agent.export_config()', the following error occurred:
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    print(agent.export_config())
  File "/workplace/rl-framework/core/agent.py", line 78, in export_config
    param_dict = {p: str(getattr(self, p)) for p in get_config_params(Agent.__init__)}
  File "/workplace/rl-framework/core/agent.py", line 78, in <dictcomp>
    param_dict = {p: str(getattr(self, p)) for p in get_config_params(Agent.__init__)}
AttributeError: 'PPOAgent' object has no attribute 'args'

**Comment by AltmanD** [comment]
Fixed

**Comment by AltmanD** [comment]
Fixed in [commit b349c26](https://github.com/guikarist/rl-framework/pull/29/commits/b349c266769464ece95761c1d5a4dd27ba2ea56f)

**Comment by terryzhao127** [comment]
> Fixed in [commit b349c26](https://github.com/guikarist/rl-framework/pull/29/commits/b349c266769464ece95761c1d5a4dd27ba2ea56f)

Fixed in a similar way in #30.
